{"client.labwi.sva.de": {"errata": [{"id": 9, "pulp_id": "FEDORA-EPEL-2020-68a03cd3b1", "title": "python-jmespath-0.9.4-2.el7", "errata_id": "FEDORA-EPEL-2020-68a03cd3b1", "issued": "2020-05-10", "updated": "2021-03-23", "severity": "None", "description": "Make jp.py use python2 again.", "solution": "", "summary": "python-jmespath-0.9.4-2.el7 bugfix update", "uuid": "FEDORA-EPEL-2020-68a03cd3b1", "name": "python-jmespath-0.9.4-2.el7", "type": "bugfix", "cves": [], "bugs": [{"bug_id": "1826380", "href": "https://bugzilla.redhat.com/show_bug.cgi?id=1826380"}], "hosts_available_count": 1, "hosts_applicable_count": 1, "packages": ["python2-jmespath-0.9.4-2.el7.noarch", "python36-jmespath-0.9.4-2.el7.noarch", "python-jmespath-0.9.4-2.el7.src"], "module_streams": [], "installable": true}], "params": {"katprep_virt": "vc6.labwi.sva.de", "katprep_virt_name": "Katello-Client", "katprep_virt_snapshot": "1", "katprep_virt_type": "pyvmomi", "ip": "10.10.153.83", "ip6": "", "name": "client.labwi.sva.de", "operatingsystem_name": "CentOS-7", "location_name": "Wiesbaden", "environment_name": null, "organization_name": "SVA GmbH", "owner": "Admin User"}, "verification": {"virt_snapshot": true, "virt_cleanup": true}}}